[package]
name = "amsterdam"
version = "0.1.0"
authors = ["Felipe Rocha <felipellrocha@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.8.1", features = ["serde", "v4"] }
chrono = "0.4.11"
crypto-hash = "0.3.4"
